Music Store/Models/CreditCard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Music_Store.Models
{
    public class CreditCard
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public string CreditCardNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Provice { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }

        public Customer Customer { get; set; }
    }
}

Music Store/Models/ViewModels/CreditCardViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Music_Store.Models.ViewModels
{
    public class CreditCardViewModel
    {

        public int ID { get; set; }

        public int CustomerID { get; set; }

        [Required(ErrorMessage = "Credit card number is required")]
        [DataType(DataType.Text)]
        [Display(Name = "Credit Card")]
        public string CreditCardNumber { get; set; }

        [Required(ErrorMessage = "First name is required!")]
        [DataType(DataType.Text)]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last name is required!")]
        [DataType(DataType.Text)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Address is required!")]
        [DataType(DataType.Text)]
        [Display(Name = "Address is required")]
        public string Address { get; set; }

        [Required(ErrorMessage = "City is required!")]
        [DataType(DataType.Text)]
        [Display(Name = "City is required")]
        public string City { get; set; }

        [Required(ErrorMessage = "Province is required!")]
        [DataType(DataType.Text)]
        [Display(Name = "Province is required")]
        public string Provice { get; set; }

        [Required(ErrorMessage = "Postal code is required!")]
        [DataType(DataType.Text)]
        [Display(Name = "Postal code is required")]
        public string PostalCode { get; set; }

        [Required(ErrorMessage = "Country is required!")]
        [DataType(DataType.Text)]
        [Display(Name = "Country is required")]
        public string Country { get; set; }
    }
}

Music Store/Controllers/CreditCardController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Music_Store.Data;
using Music_Store.Models;
using Music_Store.Models.ViewModels;
using Music_Store.Services;


namespace Music_Store.Controllers
{
    [Authorize(Roles = nameof(Customer))]
    public class CreditCardController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly ICartsService _service;
        private readonly UserManager<User> _userManager;

        public CreditCardController(ApplicationDbContext context, ICartsService service, UserManager<User> userManager)

        {
            _context = context;
            _service = service;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            User user = await _userManager.GetUserAsync(User);
            int customerID = user.CustomerID.Value;

            var creditCardViewModels = _context.Customers.Where(c => c.ID == customerID).SelectMany(c => c.CreditCards).Select(cc => new CreditCardViewModel
            {
                ID = cc.ID,
                CustomerID = cc.CustomerID,
                CreditCardNumber = cc.CreditCardNumber,
                FirstName = cc.FirstName,
                LastName = cc.LastName,
                Address = cc.Address,
                City = cc.City,
                Provice = cc.Provice,
                PostalCode = cc.PostalCode,
                Country = cc.Country

            }).AsEnumerable();
            return View(creditCardViewModels);
        }

        public IActionResult Create()
        {
            return View(new CreditCardViewModel());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] CreditCardViewModel creditCardViewModel, string returnUrl = null)
        {
            if (!ModelState.IsValid)
            {
                return View(creditCardViewModel);
            }

            User user = await _userManager.GetUserAsync(User);
            int customerID = user.CustomerID.Value;

            var creditCard = new CreditCard();
            creditCard.CreditCardNumber = creditCardViewModel.CreditCardNumber;
            creditCard.FirstName = creditCardViewModel.FirstName;
            creditCard.LastName = creditCardViewModel.LastName;
            creditCard.Address = creditCardViewModel.Address;
            creditCard.City = creditCardViewModel.City;
            creditCard.Provice = creditCardViewModel.Provice;
            creditCard.PostalCode = creditCardViewModel.PostalCode;
            creditCard.Country = creditCardViewModel.Country;
            creditCard.CustomerID = customerID;


            // TODO: put info from creditCardViewModel to CreditCard model
            _context.Add(creditCard);
            _context.SaveChanges();            
            
            var page = (string)TempData["previousPage"];
            if (page.Equals("checkoutFromCart", StringComparison.OrdinalIgnoreCase))
            {
                returnUrl = returnUrl ?? Url.Content("~/Checkout/Create");
                TempData["previousPage"] = "cart";
                return LocalRedirect(returnUrl);
            }
            else if (page.Equals("creditIndexPage", StringComparison.OrdinalIgnoreCase))
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View("Error", new ErrorViewModel());
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int customerID, [FromForm] CreditCardViewModel vm)
        {
            var creditCard = _context.Customers.Where(c => c.ID == customerID).SelectMany(c => c.CreditCards).Where(cc => cc.ID == vm.ID).SingleOrDefault();
            _context.Remove(creditCard);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Music Store/Views/CreditCard/Create.cshtml
@model Music_Store.Models.ViewModels.CreditCardViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    
}



<div style="margin-top: 3em;">
    <div style="margin-bottom: 1em;">
        <span class="title">Add a credit card</span>
    </div>
        <form method="post" asp-action="Create">

            <label for="creditcard">Credit Card*</label><br />
            <input type="text" id="creditcard" name="creditcardnumber"><br />
            <span asp-validation-for="CreditCardNumber" class="text-danger"></span><br />

            <label for="fname">First Name</label><br />
            <input type="text" id="fname" name="firstname"><br />
            <span asp-validation-for="FirstName" class="text-danger"></span><br />

            <label for="lname">Last Name</label><br />
            <input type="text" id="lname" name="lastname"><br />
            <span asp-validation-for="LastName" class="text-danger"></span><br />

            <label for="address">Address</label><br />
            <input type="text" id="address" name="address"><br />
            <span asp-validation-for="Address" class="text-danger"></span><br />

            <label for="city">City</label><br />
            <input type="text" id="city" name="city"><br />
            <span asp-validation-for="City" class="text-danger"></span><br />

            <label for="postalcode">Postal Code</label><br />
            <input type="text" id="postalcode" name="postalcode"><br />
            <span asp-validation-for="PostalCode" class="text-danger"></span><br />

            <label for="Provice">Province</label><br />
            <select id="Provice" name="Provice">
                <option value="Alberta">Alberta</option>
                <option value="British Columbia">British Colombia</option>
                <option value="Manitoba">Manitoba</option>
                <option value="New Brunswick">New Brunswick</option>
                <option value="Newfoundland and Labrador">Newfoundland and Labrador</option>
                <option value="North West Territories">Northwest Territorries</option>
                <option value="Nova Scotia">Nova Scotia</option>
                <option value="Nunavut">Nunavut</option>
                <option value="Ontario">Ontario</option>
                <option value="Prince Edward Island">Prince Edward Island</option>
                <option value="Quebec">Quebec</option>
                <option value="Saskatchewan">Saskatchewan</option>
                <option value="Yukon">Yukon</option>
            </select><br />
            <span></span><br />

            <label for="country">Country</label><br />
            <select id="country" name="country">
                <option value="Canada">Canada</option>
                <option value="USA">USA</option>
            </select>
            <span></span><br /><br />


            <input type="submit" value="Submit">

        </form>
    </div>

Music Store/Views/CreditCard/Index.cshtml
@model IEnumerable<Music_Store.Models.ViewModels.CreditCardViewModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    TempData["previousPage"] = "creditIndexPage";
}


<div style="margin-top: 3em;">
    <div style="margin-bottom: 1em;">
        <span class="title">List of all Credit cards</span>
        <a asp-controller="CreditCard" asp-action="Create" title="Add new Credit Card" style="margin-left: 3em;">
            <span>Add new credit card</span>
        </a>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    <span>Card Number</span>
                </th>
                <th>
                    <span>First Name</span>
                </th>
                <th>
                    <span>Last Name</span>
                </th>
                <th>
                    <span>Address</span>
                </th>
                <th>
                    <span>City</span>
                </th>
                <th>
                    <span>Provice</span>
                </th>
                <th>
                    <span>Postal Code</span>
                </th>
                <th>
                    <span>Country</span>
                </th>
                <th>
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var creditCard in Model)
            {
                <tr>
                    <td style="padding-top: 28px;">
                        <span style="font-size: 14px;">@creditCard.CreditCardNumber</span>
                    </td>
                    <td style="padding-top: 28px;">
                        <span style="font-size: 14px;"> @creditCard.FirstName</span>
                    </td>
                    <td style="padding-top: 28px;">
                        <span style="font-size: 14px;">@creditCard.LastName</span>
                    </td>
                    <td style="padding-top: 28px;">
                        <span style="font-size: 14px;"> @creditCard.Address</span>
                    </td>
                    <td style="padding-top: 28px;">
                        <span style="font-size: 14px;">@creditCard.City</span>
                    </td>
                    <td style="padding-top: 28px;">
                        <span style="font-size: 14px;"> @creditCard.Provice</span>
                    </td>
                    <td style="padding-top: 28px;">
                        <span style="font-size: 14px;">@creditCard.PostalCode</span>
                    </td>
                    <td style="padding-top: 28px;">
                        <span style="font-size: 14px;"> @creditCard.Country</span>
                    </td>
                    <td style="padding-top: 28px;">
                        <form method="post" asp-action="Edit" title="Delete">
                            <input class="input-img" type="image" src="~/res/images/etc/delete.png" />
                            <input type="hidden" name="ID" value="@creditCard.ID" />
                            <input type="hidden" name="customerID" value="@creditCard.CustomerID" />
                        </form>
                    </td>
                </tr>
            }
        </tbody>

    </table>
</div>