Music Store/Models/Artist.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Music_Store.Models
{
    public class Artist
    {
        public int ID { get; set; }
        public string Stagename { get; set; }
        public string Fullname { get; set; }
        public string ImagePath { get; set; }
        public int DebutYear{ get; set; }

        public ICollection<Song> Songs { get; set; } = new List<Song>();
        public ICollection<Album> Albums { get; set; } = new List<Album>();
    }
}

Music Store/Models/ViewModels/ArtistViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Music_Store.Models.ViewModels
{
    public class ArtistViewModel
    {
        public int ID { get; set; }

        [Display(Name = "Full Name")]
        public string FullName { get; set; }
        public string StageName { get; set; }
        public string ImagePath{ get; set; }

        [Display(Name = "Debut Year")]
        public int DebutYear { get; set; }

        [Display(Name = "Image")]
        public IFormFile ImageFile { get; set; }

        public IEnumerable<string> Genres { get; set; }
        public IEnumerable<ArtistAlbumViewModel> Albums { get; set; }
        public IEnumerable<AlbumSongViewModel> Songs { get; set; }
    }
}

Music Store/Controllers/ArtistsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Music_Store.Data;
using Music_Store.Models;
using Music_Store.Models.ViewModels;
using Music_Store.Services;

namespace Music_Store.Controllers
{
    public class ArtistsController : Controller
    {
        private const string BASE_PATH_SAVE = "~/res/newImages/artists/";

        private readonly ApplicationDbContext _context;
        private readonly IArtistsService _service;
        private readonly string basePath;

        public ArtistsController(ApplicationDbContext context, IArtistsService service, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _service = service;
            string rootPath = webHostEnvironment.WebRootPath;
            basePath = Path.Combine(rootPath, "res", "newImages", "artists");
        }

        // GET: Artists
        public async Task<IActionResult> Index()
        {
            return View(await _context.Artists.ToListAsync());
        }

        // GET: Artists/5/Details
        [Route("Artists/{id}/Details")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artistVm = await _service.GetArtistOrNullAsync(id.Value);
            if (artistVm == null)
            {
                return NotFound();
            }

            return View(artistVm);
        }

        // GET: Artists/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Artists/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,StageName,FullName,ImagePath,ImageFile,DebutYear")] ArtistViewModel artistVm,
            Image image)
        {
            string extension = Path.GetExtension(artistVm.ImageFile.FileName);
            string fileName = artistVm.FullName + extension;
            string path = Path.Combine(basePath, fileName);

            // find
            using (var fileStream = new FileStream(path, FileMode.Create))
            {
                await image.ImageFile.CopyToAsync(fileStream);
            }
            Artist artist = new Artist
            {
                Stagename = artistVm.StageName,
                Fullname = artistVm.FullName,
                DebutYear = artistVm.DebutYear,
                ImagePath = BASE_PATH_SAVE + fileName
            };
            if (ModelState.IsValid)
            {
                _context.Add(artist);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(artistVm);
        }

        // GET: Artists/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists.FindAsync(id);
            if (artist == null)
            {
                return NotFound();
            }
            var artistVm = new ArtistViewModel
            {
                ID = artist.ID,
                StageName = artist.Stagename,
                FullName = artist.Fullname,
                ImagePath = artist.ImagePath,
                DebutYear = artist.DebutYear
            };
            return View(artistVm);
        }

        // POST: Artists/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Stagename,Fullname,ImagePath,ImageFile, DebutYear")] ArtistViewModel artistVm)
        {
            string extension = "";
            string fileName = "";
            if (artistVm.ImageFile != null)
            {
                string path = Path.Combine(basePath, fileName);
                extension = Path.GetExtension(artistVm.ImageFile.FileName);
                fileName = artistVm.FullName + extension;
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    await artistVm.ImageFile.CopyToAsync(fileStream);
                }
            }
            else
            {
                fileName = artistVm.FullName + ".png";
            }
            if (id != artistVm.ID)
            {
                return NotFound();
            }
            Artist updatedArtist = new Artist
            {
                ID = artistVm.ID,
                Stagename = artistVm.StageName,
                Fullname = artistVm.FullName,
                DebutYear = artistVm.DebutYear,
                ImagePath = BASE_PATH_SAVE + fileName
            };

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(updatedArtist);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ArtistExists(artistVm.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(updatedArtist);
        }

        // GET: Artists/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var artist = await _context.Artists
                .FirstOrDefaultAsync(m => m.ID == id);
            if (artist == null)
            {
                return NotFound();
            }

            return View(artist);
        }

        // POST: Artists/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var artist = await _context.Artists.FindAsync(id);
            _context.Artists.Remove(artist);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ArtistExists(int id)
        {
            return _context.Artists.Any(e => e.ID == id);
        }
    }
}

Music Store/Controllers/CartsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Internal;
using Music_Store.Data;
using Music_Store.Helpers;
using Music_Store.Models;
using Music_Store.Models.ViewModels;
using Music_Store.Services;

namespace Music_Store.Controllers
{
    public class CartsController : Controller
    {
        private const string SESSION_KEY = "music_store";

        private readonly ApplicationDbContext _context;
        private readonly ICartsService _service;
        private readonly SignInManager<User> _signInManager;
        private readonly UserManager<User> _userManager;

        public CartsController(ApplicationDbContext context, ICartsService service, SignInManager<User> signInManager, UserManager<User> userManager)
        {
            _context = context;
            _service = service;
            _signInManager = signInManager;
            _userManager = userManager;
        }

        // GET: Carts
        public async Task<IActionResult> Index()
        {
            CartViewModel cartVm = await _service.GetCartFromSessionAsync(HttpContext, SESSION_KEY);

            cartVm = await MergeCartsIfLogedIn(cartVm);

            return View(cartVm);
        }

        // POST: Carts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string type, int id)
        {
            CartViewModel cartVm = await _service.GetCartFromSessionAsync(HttpContext, SESSION_KEY);

            if (!cartVm.Items.Any(i => i.Category == type && i.ItemID == id))
            {
                CartItemViewModel cartItemVm = await _service.CreateCartItemAsync(type, id);
                cartVm.AddItem(cartItemVm);
            }

            cartVm = await MergeCartsIfLogedIn(cartVm);

            return View("Index", cartVm);
        }

        public async Task<IActionResult> CreateWithoutRedirect(string type, int id)
        {
            CartViewModel cartVm = await _service.GetCartFromSessionAsync(HttpContext, SESSION_KEY);

            if (!cartVm.Items.Any(i => i.Category == type && i.ItemID == id))
            {
                CartItemViewModel cartItemVm = await _service.CreateCartItemAsync(type, id);
                cartVm.AddItem(cartItemVm);
            }

            cartVm = await MergeCartsIfLogedIn(cartVm);

            return RedirectToAction("Index", "Wishlist");
        }

        // POST: Carts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int customerID, [FromForm] CartItemViewModel vm, string action)
        {
            if (_signInManager.IsSignedIn(User) && User.IsInRole(nameof(Customer)))
            {
                var itemID = vm.ItemID;
                if (!await _service.CheckIfItemExistsInCartAsync(customerID, itemID))
                {
                    return NotFound();
                }

                await _service.RemoveItem(customerID, itemID);
            }
            else
            {
                var cartVm = await _service.GetCartFromSessionAsync(HttpContext, SESSION_KEY);

                cartVm.Items.Remove(vm);

                HttpContext.Session.SetObjectAsJson(SESSION_KEY, cartVm);
            }

            if (action != null && action == "move")
            {
                return RedirectToAction("CreateWithoutRedirect", "Wishlist", new { type = vm.Category, id = vm.ItemID });
            }

            return RedirectToAction(nameof(Index));
        }

        //private async Task<CartViewModel> GetCartFromSessionAsync(HttpContext httpContext)
        //{
        //    return await Task.Run(() =>
        //    {
        //        var cartVm = httpContext.Session.GetObjectFromJson<CartViewModel>(SESSION_KEY);

        //        if (cartVm == null)
        //        {
        //            cartVm = new CartViewModel();
        //        }

        //        return cartVm;
        //    });
        //}

        private async Task<CartViewModel> MergeCartsIfLogedIn(CartViewModel cartViewModel)
        {
            if (_signInManager.IsSignedIn(User) && User.IsInRole(nameof(Customer)))
            {
                var user = await _userManager.GetUserAsync(User);
                var customerID = user.CustomerID.Value;

                foreach (var i in cartViewModel.Items)
                {
                    if (!await _service.CheckIfItemExistsInCartAsync(customerID, i.ItemID))
                    {
                        await _service.AddItemToCartAsync(i, customerID);
                    }
                }

                cartViewModel = await _service.GetCartFromCustomerAsync(customerID);

                HttpContext.Session.Remove(SESSION_KEY);
            }
            else
            {
                HttpContext.Session.SetObjectAsJson(SESSION_KEY, cartViewModel);
            }

            return cartViewModel;
        }

        
        public ActionResult Checkout()
        {
            return View("Checkout");
        }
    }
}

Music Store/Views/Artists/Create.cshtml
@model Music_Store.Models.ViewModels.ArtistViewModel

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h4>Create Artist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Stage Name</label>
                <input asp-for="StageName" class="form-control" />
                <span asp-validation-for="StageName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label  class="control-label">Full Name</label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group"><input asp-for="ImageFile" accept="image/*" /></div>
            
            <div class="form-group">
                <label class="control-label">Debut Year</label>
                <input asp-for="DebutYear" class="form-control" />
                <span asp-validation-for="DebutYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Music Store/Views/Artists/Delete.cshtml
@model Music_Store.Models.Artist

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Artist</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Stagename)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Stagename)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fullname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fullname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DebutYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DebutYear)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Music Store/Views/Artists/Details.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<User> SignInManager
@model Music_Store.Models.ViewModels.ArtistViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";

    const int STARS_IMAGE_SIZE = 94;
}

<div style="margin-top: 3em;">
    <div>
        <span class="title">@Model.StageName</span>

        @if (SignInManager.IsSignedIn(User) && User.IsInRole("Employee"))
        {
            <a class="btn btn-danger btn-margin" style="float: right" asp-action="Delete" asp-route-id="@Model.ID">Delete</a>
            <a class="btn btn-orange btn-margin" style="float: right" asp-action="Edit" asp-route-id="@Model.ID">Edit</a>
        }
    </div>

    @*-- Artist Details --*@
    <hr />
    <div class="row" style="margin-left: 7em;">
        <img class="col-sm-4 img-fluid" src="@Model.ImagePath" asp-append-version="true" />
        <div class="col-sm-8" style="display: flex; flex-direction: column">
            <div style="display: flex; margin-top: 2em;">
                <dl style="flex: 1;">
                    <dt>@Html.DisplayNameFor(model => model.FullName)</dt>
                    <dt>@Html.DisplayNameFor(model => model.Genres)</dt>
                    <dt>@Html.DisplayNameFor(model => model.DebutYear)</dt>
                </dl>
                <dl style="flex: 2;">
                    <dd>@Model.FullName</dd>
                    <dd>
                        @foreach (var genre in Model.Genres)
                        {
                            @(genre + " ")
                        }
                    </dd>
                    <dd>@Model.DebutYear</dd>
                </dl>
            </div>
        </div>
    </div>

    @*-- Albums --*@
    <div class="sub-div">
        <span class="sub-title">@Model.Albums.Count() Album(s)</span>
        <hr />

        <div style="display: flex; flex-wrap: wrap; margin-left: 20px;">
            @foreach (var album in Model.Albums)
            {
                <div style="width:190px; margin: 0 10px 40px 10px;">
                    <img src="@album.ImagePath" style="margin-bottom: 7px; width: 180px;" asp-append-version="true" />
                    <a asp-controller="Albums" asp-action="Details" asp-route-id="@album.ID" title="Album" style="font-size: 15px; padding-top: 7px; color: unset !important;">@album.Name</a>
                    <div style="line-height: 1;">
                        <a asp-controller="Artists" asp-action="Details" asp-route-id="@Model.ID" title="Artist" style="font-size: 14px; color: darkgray;">@Model.StageName</a>
                    </div>
                </div>
            }
        </div>
    </div>

    @*-- Songs --*@
    <div class="sub-div">
        <span class="sub-title">@Model.Songs.Count() Song(s)</span>
        <hr />

        @foreach (var song in Model.Songs)
        {
            <div style="display: flex; position: relative;">
                <span style="flex: 1;">
                    <a asp-controller="Songs" asp-action="Details" asp-route-id="@song.ID" title="Song" style="color: unset !important;">
                        @song.Name
                    </a>
                </span>
                <span style="flex: 1;">
                    <a asp-controller="Artists" asp-action="Details" asp-route-id="@Model.ID" title="Artist" style="color: darkgray;">
                        @Model.StageName
                    </a>
                </span>

                <span title="Runtime" style="flex: 0.4; padding-top: 2px;">@TimeSpan.FromSeconds(song.RuntimeInSec).ToString(@"mm\:ss")</span>

                <div title="Rating: @song.Rating out of 5" style="flex: 1.2; position: relative; bottom: 2px">
                    <div style="position: absolute; left:0px;">
                        <img src="~/res/images/etc/empty_stars.png" style="padding-bottom: 2px;" />
                        <span class="font-orange" style="font-size: 14px;">@song.Rating</span>
                    </div>
                    <div style="position: absolute; left:0px; overflow: hidden; width: @(STARS_IMAGE_SIZE * song.Rating / 5)px;">
                        <img src="~/res/images/etc/stars.png" style="padding-bottom: 2px;" />
                    </div>
                </div>
                <div style="flex: 0.2">
                    <form method="post" asp-controller="Carts" asp-action="Create" asp-route-type="@nameof(Song)" asp-route-id="@song.ID" title="Add to Cart">
                        <input class="input-img" type="image" src="~/res/images/etc/cart.png" />
                    </form>
                </div>
            </div>
        }
    </div>
</div>

Music Store/Views/Artists/Edit.cshtml
@model Music_Store.Models.ViewModels.ArtistViewModel
@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h4>Edit Artist</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label class="control-label">Stage Name</label>
                <input asp-for="StageName" class="form-control" />
                <span asp-validation-for="StageName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Full Name</label>
                <input asp-for="FullName" class="form-control" />
                <span asp-validation-for="FullName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <img class="col-sm-5 img-fluid" src="@Url.Content(Model.ImagePath)" asp-append-version="true" />
                <input asp-for="ImageFile" accept="image/*" />
            </div>
            <div class="form-group">
                <label asp-for="DebutYear" class="control-label"></label>
                <input asp-for="DebutYear" class="form-control" />
                <span asp-validation-for="DebutYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Music Store/Views/Artists/Index.cshtml
@model IEnumerable<Music_Store.Models.Artist>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Stagename)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Fullname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DebutYear)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Stagename)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fullname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DebutYear)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>